// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'followIcons': string;
  'pageContent': string;
  'pageFooter': string;
  'pageHeader': string;
}
export const cssExports: CssExports;
export default cssExports;
