// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'boxed': string;
  'header': string;
  'homeHeader': string;
  'linksWithIcons': string;
  'ui': string;
}
export const cssExports: CssExports;
export default cssExports;
